jobs:
  build:
    name: Workflow
    runs-on: ubuntu-20.04

    steps:
      - name: Startup
        uses: actions/checkout@v2
      - name: Get Tools
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Run Tests
        run: ./main/check

name: Main

on:
  schedule:
    - cron: "55 */6 * * *"
